{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(server_requests[$__interval])"
    }
   ]
  },
  {
   "title": "Sent bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "server_sent_bytes" }
   ]
  },
  {
   "title": "Received bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "server_received_bytes" }
   ]
  },
  {
   "title": "Req/s per socket",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(client_requests[5m])", "legendFormat": "{{socketNumber}}" }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(server_response_nanoseconds_bucket[5m]))"
    }
   ]
  }
 ]
}